name: unlearnpipeline  #for cuda 13.0
channels:
  - defaults
dependencies:
  - python=3.11
  - pip=25.3
  - setuptools=80.9.0
  - wheel=0.45.1
  - pip:

      - torch==2.9.1
      - torchvision==0.24.1
      # CUDA 13 wheel index
      # pip install torch==2.9.1 torchvision==0.24.1 \
      #   --index-url https://download.pytorch.org/whl/cu130
      
      - accelerate==1.10.1
      - datasets==4.5.0
      - huggingface-hub>=1.8.0
      - tokenizers==0.22.2
      - transformers==4.57.6
      - safetensors==0.7.0
      
      - openai==2.15.0
      - numpy==2.0.2
      - pandas==2.3.3
      - pyarrow==21.0.0
      - pillow==11.3.0
      - pyyaml==6.0.3
      - tqdm==4.67.1
      - requests==2.32.5
      - python-dotenv==1.2.1
      - pydantic==2.12.5